// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTUcPsP8Gn-d0MW3qjN4koPTe1LSURHGk',
    appId: '1:713141886917:web:79ad900afbd8f46184b5ac',
    messagingSenderId: '713141886917',
    projectId: 'chat-app-nullo',
    authDomain: 'chat-app-nullo.firebaseapp.com',
    storageBucket: 'chat-app-nullo.firebasestorage.app',
    measurementId: 'G-GWH0N4BT9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1I0x04r6L-XyWMEM6Fixdgi4zB3a4r40',
    appId: '1:713141886917:android:09394ac789aff4d484b5ac',
    messagingSenderId: '713141886917',
    projectId: 'chat-app-nullo',
    storageBucket: 'chat-app-nullo.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTUcPsP8Gn-d0MW3qjN4koPTe1LSURHGk',
    appId: '1:713141886917:web:480e02429be7bd1c84b5ac',
    messagingSenderId: '713141886917',
    projectId: 'chat-app-nullo',
    authDomain: 'chat-app-nullo.firebaseapp.com',
    storageBucket: 'chat-app-nullo.firebasestorage.app',
    measurementId: 'G-3V7VSBHVLJ',
  );
}
